<ul class = "text-sm px-12">
    <li class = "mb-6"> <a href="{{$newproduct ? '/products/create' : '/products/'.$pid.'/edit'}}" class = "flex {{$step==1 ? 'font-bold text-blue-600' : 'text-gray-500'}}"> <span class = "flex-shrink-0 block w-6 h-6 rounded-full {{$step==1 ? 'bg-blue-600' : 'bg-gray-700'}} text-white flex justify-center items-center mr-4"> 1 </span> <span class = ""> Create Product </span> </a> </li>
    <li class = "mb-6"> <a href="{{$newproduct ? '#' : '/products/'.$pid.'/variants'}}" class = "flex {{$step==2 ? 'font-bold text-blue-600' : 'text-gray-500'}}"> <span class = "flex-shrink-0 block w-6 h-6 rounded-full {{$step==2 ? 'bg-blue-600' : 'bg-gray-700'}} text-white flex justify-center items-center mr-4"> 2 </span> <span class = ""> Product Variants </span> </a> </li>
    <li class = "mb-6"> <a href="{{$newproduct ? '#' : '/products/'.$pid.'/inventory/create'}}" class = "flex {{$step==3 ? 'font-bold text-blue-600' : 'text-gray-500'}}"> <span class = "flex-shrink-0 block w-6 h-6 rounded-full {{$step==3 ? 'bg-blue-600' : 'bg-gray-700'}} text-white flex justify-center items-center mr-4"> 3 </span> <span class = ""> Stock Management </span> </a> </li>
    <li class = "mb-6"> <a href="{{$newproduct ? '#' : '/products/'.$pid.'/highlights/create'}}" class = "flex {{$step==4 ? 'font-bold text-blue-600' : 'text-gray-500'}}"> <span class = "flex-shrink-0 block w-6 h-6 rounded-full {{$step==4 ? 'bg-blue-600' : 'bg-gray-700'}} text-white flex justify-center items-center mr-4"> 4 </span> <span class = ""> Add Product Highlights </span> </a> </li>
    <li class = "mb-6"> <a href="{{$newproduct ? '#' : '/products/'.$pid.'/banners/create'}}" class = "flex {{$step==5 ? 'font-bold text-blue-600' : 'text-gray-500'}}"> <span class = "flex-shrink-0 block w-6 h-6 rounded-full {{$step==5 ? 'bg-blue-600' : 'bg-gray-700'}} text-white flex justify-center items-center mr-4"> 5 </span> <span class = ""> Add Banner Section </span> </a> </li>
    <li class = "mb-6"> <a href="{{$newproduct ? '#' : '/products/'.$pid.'/attributes/create'}}" class = "flex {{$step==6 ? 'font-bold text-blue-600' : 'text-gray-500'}}"> <span class = "flex-shrink-0 block w-6 h-6 rounded-full {{$step==6 ? 'bg-blue-600' : 'bg-gray-700'}} text-white flex justify-center items-center mr-4"> 6 </span> <span class = ""> Add Attributes / Spec </span> </a> </li>
    <li class = "mb-6"> <a href="{{$newproduct ? '#' : '/products/'.$pid.'/offers/create'}}" class = "flex {{$step==7 ? 'font-bold text-blue-600' : 'text-gray-500'}}"> <span class = "flex-shrink-0 block w-6 h-6 rounded-full {{$step==7 ? 'bg-blue-600' : 'bg-gray-700'}} text-white flex justify-center items-center mr-4"> 7 </span> <span class = ""> Run Offers on product </span> </a> </li>
    <li class = "mb-6"> <a href="{{$newproduct ? '#' : '/products/'.$pid.'/attachments/create'}}" class = "flex {{$step==8 ? 'font-bold text-blue-600' : 'text-gray-500'}}"> <span class = "flex-shrink-0 block w-6 h-6 rounded-full {{$step==8 ? 'bg-blue-600' : 'bg-gray-700'}} text-white flex justify-center items-center mr-4"> 8 </span> <span class = ""> Upload Attachments </span> </a> </li>
</ul>